blog:
  title: "DevPub"
  subtitle: "Блог о разработке"
  phone: "+7-911-826-52-11"
  email: "diesel-z@yandex.ru"
  copyright: "Андрей Ларионов"
  copyrightFrom: "2019"


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  security:
    user:
      name: "andrew"
      password: "1456"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL55Dialect"
    show-sql: "true"
  datasource:
    url: "jdbc:mysql://localhost:3306/blogDB?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  mail:
    host: "smtp.yandex.ru"
    username: "uw@dru.su"
    password: "12345678"
    port: "465"
    protocol: "smtps"
  #flyway:
  #  enabled: "false"

mail:
    debug: "true"