blog:
  title: "DevPub"
  subtitle: "Блог о разработке"
  phone: "+7-911-826-52-11"
  email: "diesel-z@yandex.ru"
  copyright: "Андрей Ларионов"
  copyrightFrom: "2019"


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL55Dialect"
    show-sql: "true"
  datasource:
    url: "jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  mail:
    host: "smtp.yandex.ru"
    username: "uw@dru.su"
    password: "12345678"
    port: "465"
    protocol: "smtps"

mail:
    debug: "true"

cloudinary:
   cloud:
     name: ${CLOUDINARY_CLOUD_NAME:unevbe14}
   api:
     key: ${CLOUDINARY_API_KEY:998333224815347}
     secret: ${CLOUDINARY_API_SECRET:Z3_UjO2cAOKy-7p-k_BcQWENLX8}

upload:
  file:
    types: png,jpg,jpeg
